os: osx
jobs:
  include:
  - osx_image: xcode10.1
    name: xcode10.1 openjdk11
  - osx_image: xcode9
    name: xcode9 oraclejdk8
  - osx_image: xcode10
    name: xcode10 oraclejdk10
language: java
jdk:
  - oraclejdk8
  - openjdk11
  - oraclejdk10
install: skip
script: skip
notifications:
  email: never
