language: php
install: php --version
script: php --version grep -q '7\.2'
jobs:
  include:
    - env: where=precise
      dist: precise
    - env: where=trusty
      dist: trusty
    - env: where=xenial
      dist: xenial
      group: edge
    - env: where=xcode10
      os: osx
      osx_image: xcode10
    - env: where=xcode9.4
      os: osx
      osx_image: xcode9.4
    - env: where=xcode9.3
      os: osx
      osx_image: xcode9.3
    - env: where=xcode9.2
      os: osx
      osx_image: xcode9.2
    - env: where=xcode9.1
      os: osx
      osx_image: xcode9.1
    - env: where=xcode9
      os: osx
      osx_image: xcode9
    - env: where=xcode8.3
      os: osx
      osx_image: xcode8.3
    - env: where=xcode8
      os: osx
      osx_image: xcode8
    - env: where=xcode7.3
      os: osx
      osx_image: xcode7.3
    - env: where=xcode6.4
      os: osx
      osx_image: xcode6.4
notifications:
  email: false
