language: python
install: skip
addons:
  apt:
    packages:
      - x11-apps
script:
  - sudo apt-get update
  - sudo apt-get install tree
  - cat /etc/apt/apt.conf.d/99-noredirect
notifications:
  email: never
