language: bash
sudo: required
script: heroku --version
install: skip
matrix:
    include:
        - env: dist=trusty
          dist: trusty
        - env: dist=precise
          dist: precise
notifications:
  email: never

