sudo: false
language: php
php: 5.5
matrix:
    include:
        - env: "trace=true"
          trace: true
        - env: "trace=false"
          trace: false
install: skip
script: cat /tmp/build.trace
notifications:
  email: false
