language: java
os: osx
matrix:
  include:
    - env: run=jdk10_new
      osx_image: xcode10
      jdk: oraclejdk10
    - env: run=jdk10_old
      osx_image: xcode9.4
      jdk: oraclejdk10
    - env: run=jdk8
      osx_image: xcode9.3
      jdk: oraclejdk8
    - env: run=jdk8_old
      osx_image: xcode8
      jdk: oraclejdk8
install: skip
script:
  - which java
  - java -version
notifications:
  email: false
