sudo: prettyplease
language: java
jdk: oraclejdk11
matrix:
    include:
        - env: test=trusty_oraclejdk10
          dist: trusty
          jdk: oraclejdk10
        - env: test=trusty_oraclejdk8
          dist: trusty
          jdk: oraclejdk8
        - env: test=trusty_openjdk11
          dist: trusty
          jdk: openjdk11
install: skip
script:
    - which java
    - java -version
notifications:
  email: false
