sudo: prettyplease
language: java
jdk: oraclejdk11
matrix:
    include:
        - env: test=xenial_oraclejdk10
          dist: xenial
          jdk: oraclejdk10
        - env: test=xenial_openjdk11
          dist: xenial
          jdk: openjdk11
        - env: test=xenial_openjdk9
          dist: xenial
          jdk: openjdk8
install: skip
script:
    - which java
    - java -version
notifications:
  email: false
