language: java
jobs:
  include:
    - name: symlink linux
      jdk: openjdk11
    - name: no synlink linux
      jdk: oraclejdk11
    - name: osx
      os: osx
      osx_image: xcode9
      jdk: openjdk11
dist: trust
install: skip
script:
  - java -version
  - ls -lR $JAVA_HOME | grep cacerts
notifications:
  email: never
