jobs:
    include:
        - env: sudo=yes
          sudo: yes
        - env: sudo=no
          sudo: false
language: java
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
install: skip
script: skip
notifications:
  email: never

