language: java
dist: trusty
jobs:
  include:
    - name: stable
      group: stable
    - name: edge
      group: edge
    - name: dev
      group: dev
install: skip
script: cat /etc/hosts
notifications:
  email: never
