language: python
jobs:
  include:
    - name: xenial-stable
      dist: xenial
    - name: xenial-deprecated
      dist: xenial
      group: deprecated
    - name: trusty
      dist: trusty
    - name: precise
      dist: precise
addons:
  mariadb: 10.1
install: skip
script: skip
notifications:
  email: never
