language: python
install: skip
jobs:
  include:
    - name: precise
      dist: precise
    - name: trusty
      dist: trusty
    - name: xenial
      dist: xenial
addons:
  apt:
    packages:
      - x11-apps
script:
  - sudo apt-get update
  - sudo apt-get install tree
  - cat /etc/apt/apt.conf.d/99-noredirect
notifications:
  email: never
