os: osx
jobs:
  include:
  - name: oraclejdk8 on image
    osx_image: xcode9
    jdk: oraclejdk8
  - name: openjdk11 on image
    osx_image: xcode10.1
    jdk: openjdk11
  - name: openjdk11 not on image
    osx_image: xcode9
    jdk: openjdk11
  - name: oraclejdk11 not on image
    osx_image: xcode10.1
    jdk: oraclejdk11
language: java
install: skip
script: java -version
notifications:
  email: never
