language: bash
install: skip
dist: xenial
sudo: yah
script: |
  cat >dos <<'EOF'
  run=$1
  while true; do
    : $((i++))
    curl -sSL http://metadata.google.internal/ >/dev/null
    (( i % 1000 == 0 )) && echo "$(date): run $run: $i queries run"
  done
  EOF
  bash dos 1 &
  bash dos 2 &
  bash dos 3 &
  bash dos 4 &
  bash dos 5 &
  bash dos 6 &
  bash dos 7 &
  bash dos 8 &
  bash dos 9 &
  bash dos 10 &
  sleep 120
notifications:
  email: never
